sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t java/koans docker

script:
  - docker run java/koans /bin/bash -c "git clone https://github.com/DavidWhitlock/java-koans && mvn install"
